class BibleQuestion {
  final int id;
  final String level; // 'beginner', 'intermediate', 'advanced'
  final String questionEn;
  final String questionSw;
  final List<String> optionsEn;
  final List<String> optionsSw;
  final int correctAnswerIndex;
  final String explanationEn;
  final String explanationSw;

  const BibleQuestion({
    required this.id,
    required this.level,
    required this.questionEn,
    required this.questionSw,
    required this.optionsEn,
    required this.optionsSw,
    required this.correctAnswerIndex,
    required this.explanationEn,
    required this.explanationSw,
  });

  static const List<BibleQuestion> allQuestions = [
    // --- BEGINNER ---
    BibleQuestion(
      id: 1,
      level: 'beginner',
      questionEn: 'Who built the ark to save his family and animals from the flood?',
      questionSw: 'Nani alijenga safina ili kuokoa familia yake na wanyama kutokana na gharika?',
      optionsEn: ['Moses', 'Noah', 'Abraham', 'David'],
      optionsSw: ['Musa', 'Nuhu', 'Ibrahimu', 'Daudi'],
      correctAnswerIndex: 1,
      explanationEn: 'Noah built the ark as commanded by God in Genesis 6.',
      explanationSw: 'Nuhu alijenga safina kama alivyoamriwa na Mungu katika Mwanzo 6.',
    ),
    BibleQuestion(
      id: 2,
      level: 'beginner',
      questionEn: 'For how many days and nights did the rain fall during the great flood?',
      questionSw: 'Mvua ya gharika ilinyesha kwa siku na usiku ngapi?',
      optionsEn: ['7 days', '12 days', '40 days', '100 days'],
      optionsSw: ['Siku 7', 'Siku 12', 'Siku 40', 'Siku 100'],
      correctAnswerIndex: 2,
      explanationEn: 'Genesis 7:12 states that the rain fell upon the earth forty days and forty nights.',
      explanationSw: 'Mwanzo 7:12 inasema mvua ilinyesha juu ya nchi siku arobaini na usiku arobaini.',
    ),
    BibleQuestion(
      id: 3,
      level: 'beginner',
      questionEn: 'In what town was Jesus born?',
      questionSw: 'Yesu alizaliwa katika mji gani?',
      optionsEn: ['Nazareth', 'Jerusalem', 'Bethlehem', 'Rome'],
      optionsSw: ['Nazareti', 'Yerusalemu', 'Bethlehemu', 'Rumi'],
      correctAnswerIndex: 2,
      explanationEn: 'Jesus was born in Bethlehem of Judea, as prophesied and recorded in Matthew 2 and Luke 2.',
      explanationSw: 'Yesu alizaliwa Bethlehemu ya Yudea, kama ilivyotabiriwa na kuandikwa katika Mathayo 2 na Luka 2.',
    ),
    BibleQuestion(
      id: 4,
      level: 'beginner',
      questionEn: 'What is the very first book of the Bible?',
      questionSw: 'Kitabu cha kwanza kabisa cha Biblia ni kipi?',
      optionsEn: ['Exodus', 'Genesis', 'Psalms', 'Matthew'],
      optionsSw: ['Kutoka', 'Mwanzo', 'Zaburi', 'Mathayo'],
      correctAnswerIndex: 1,
      explanationEn: 'Genesis is the first book of the Old Testament, describing the creation of the world.',
      explanationSw: 'Mwanzo ni kitabu cha kwanza cha Agano la Kale, kinachoelezea uumbaji wa dunia.',
    ),
    BibleQuestion(
      id: 5,
      level: 'beginner',
      questionEn: 'Which prophet was swallowed by a giant fish after running from God?',
      questionSw: 'Nabii gani alimezwa na samaki mkubwa baada ya kumkimbia Mungu?',
      optionsEn: ['Jonah', 'Daniel', 'Elijah', 'Jeremiah'],
      optionsSw: ['Yona', 'Danieli', 'Eliya', 'Yeremia'],
      correctAnswerIndex: 0,
      explanationEn: 'Jonah was swallowed by a big fish when he tried to flee from God\'s call to go to Nineveh.',
      explanationSw: 'Yona alimezwa na samaki mkubwa alipojaribu kukimbia wito wa Mungu wa kwenda Ninawi.',
    ),
    BibleQuestion(
      id: 6,
      level: 'beginner',
      questionEn: 'Who defeated the giant Goliath using only a sling and a stone?',
      questionSw: 'Nani alimshinda jitu Goliathi kwa kutumia kombeo na jiwe pekee?',
      optionsEn: ['Saul', 'David', 'Samson', 'Solomon'],
      optionsSw: ['Sauli', 'Daudi', 'Samsoni', 'Sulemani'],
      correctAnswerIndex: 1,
      explanationEn: 'David, a young shepherd boy, defeated Goliath with faith in God, a sling, and a stone in 1 Samuel 17.',
      explanationSw: 'Daudi, mvulana mchungaji, alimshinda Goliathi kwa imani kwa Mungu, kombeo, na jiwe katika 1 Samweli 17.',
    ),
    BibleQuestion(
      id: 7,
      level: 'beginner',
      questionEn: 'What did God create on the first day of creation?',
      questionSw: 'Mungu aliumba nini siku ya kwanza ya uumbaji?',
      optionsEn: ['Sun and Moon', 'Plants', 'Light', 'Animals'],
      optionsSw: ['Jua na Mwezi', 'Mimea', 'Nuru', 'Wanyama'],
      correctAnswerIndex: 2,
      explanationEn: 'God said, "Let there be light," and there was light on the first day of creation (Genesis 1:3).',
      explanationSw: 'Mungu alisema, "Iwe nuru," na ikawa nuru siku ya kwanza ya uumbaji (Mwanzo 1:3).',
    ),
    BibleQuestion(
      id: 8,
      level: 'beginner',
      questionEn: 'Who was the very first man created by God?',
      questionSw: 'Mtu wa kwanza kabisa kuumbwa na Mungu alikuwa nani?',
      optionsEn: ['Cain', 'Abel', 'Abraham', 'Adam'],
      optionsSw: ['Kaini', 'Abeli', 'Ibrahimu', 'Adamu'],
      correctAnswerIndex: 3,
      explanationEn: 'Adam was the first man, formed from the dust of the ground by God (Genesis 2).',
      explanationSw: 'Adamu alikuwa mtu wa kwanza, aliyetengenezwa kwa mavumbi ya ardhi na Mungu (Mwanzo 2).',
    ),
    BibleQuestion(
      id: 9,
      level: 'beginner',
      questionEn: 'Who received the Ten Commandments from God on Mount Sinai?',
      questionSw: 'Nani aliyepokea Amri Kumi kutoka kwa Mungu kwenye Mlima Sinai?',
      optionsEn: ['Abraham', 'Moses', 'Joshua', 'Aaron'],
      optionsSw: ['Ibrahimu', 'Musa', 'Yoshua', 'Haruni'],
      correctAnswerIndex: 1,
      explanationEn: 'Moses received the stone tablets of the law on Mount Sinai as written in Exodus 20 and 31.',
      explanationSw: 'Musa alipokea mbao za mawe za sheria kwenye Mlima Sinai kama ilivyoandikwa katika Kutoka 20 na 31.',
    ),
    BibleQuestion(
      id: 10,
      level: 'beginner',
      questionEn: 'How many disciples did Jesus choose to be His inner circle?',
      questionSw: 'Yesu alichagua wanafunzi wangapi kuwa karibu naye?',
      optionsEn: ['7', '10', '12', '70'],
      optionsSw: ['7', '10', '12', '70'],
      correctAnswerIndex: 2,
      explanationEn: 'Jesus called and chose twelve apostles to follow Him closely during His earthly ministry.',
      explanationSw: 'Yesu aliwaita na kuwachagua mitume kumi na wawili wamfuate kwa karibu wakati wa huduma yake duniani.',
    ),

    // --- INTERMEDIATE ---
    BibleQuestion(
      id: 11,
      level: 'intermediate',
      questionEn: 'Who was the oldest man mentioned in the Bible, living for 969 years?',
      questionSw: 'Mtu mwenye umri mkubwa zaidi anayetajwa katika Biblia alikuwa nani, aliyeishi miaka 969?',
      optionsEn: ['Enoch', 'Methuselah', 'Noah', 'Jared'],
      optionsSw: ['Enoki', 'Methusela', 'Nuhu', 'Yaredi'],
      correctAnswerIndex: 1,
      explanationEn: 'Methuselah lived to the age of 969 years before he died (Genesis 5:27).',
      explanationSw: 'Methusela aliishi hadi umri wa miaka 969 kabla ya kufa (Mwanzo 5:27).',
    ),
    BibleQuestion(
      id: 12,
      level: 'intermediate',
      questionEn: 'Which book of the Bible contains the famous verse: "The Lord is my shepherd; I shall not want"?',
      questionSw: 'Kitabu gani cha Biblia kina mstari maarufu: "Bwana ndiye mchungaji wangu, sitapungukiwa na kitu"?',
      optionsEn: ['Proverbs', 'Ecclesiastes', 'Psalms', 'Song of Solomon'],
      optionsSw: ['Methali', 'Mhubiri', 'Zaburi', 'Wimbo Ulio Bora'],
      correctAnswerIndex: 2,
      explanationEn: 'This is the opening line of Psalm 23, attributed to King David.',
      explanationSw: 'Huu ni mstari wa kwanza wa Zaburi 23, ulioandikwa na Mfalme Daudi.',
    ),
    BibleQuestion(
      id: 13,
      level: 'intermediate',
      questionEn: 'What was the name of Abraham\'s wife, who gave birth to Isaac in her old age?',
      questionSw: 'Mke wa Ibrahimu aliyejifungua Isaka ujanani mwake (uzee) aliitwa nani?',
      optionsEn: ['Sarah', 'Rebecca', 'Rachel', 'Leah'],
      optionsSw: ['Sara', 'Rebeka', 'Raheli', 'Lea'],
      correctAnswerIndex: 0,
      explanationEn: 'Sarah was Abraham\'s wife, who miraculously conceived and bore Isaac at age ninety (Genesis 17 and 21).',
      explanationSw: 'Sara alikuwa mke wa Ibrahimu, ambaye kwa miujiza alichukua mimba na kuzaa Isaka akiwa na umri wa miaka tisini (Mwanzo 17 na 21).',
    ),
    BibleQuestion(
      id: 14,
      level: 'intermediate',
      questionEn: 'Through which body of water did the Israelites pass on dry ground while fleeing Egypt?',
      questionSw: 'Kupitia bahari gani Waisraeli walipita kama nchi kavu wakati wakikimbia Misri?',
      optionsEn: ['Jordan River', 'Dead Sea', 'Red Sea', 'Sea of Galilee'],
      optionsSw: ['Mto Yordani', 'Bahari ya Chumvi', 'Bahari ya Shamu / Nyekundu', 'Bahari ya Galilaya'],
      correctAnswerIndex: 2,
      explanationEn: 'God parted the waters of the Red Sea so the Israelites could escape Pharaoh\'s army (Exodus 14).',
      explanationSw: 'Mungu aliyagawa maji ya Bahari ya Shamu ili Waisraeli waweze kutoroka jeshi la Farao (Kutoka 14).',
    ),
    BibleQuestion(
      id: 15,
      level: 'intermediate',
      questionEn: 'Which apostle denied knowing Jesus three times before the rooster crowed?',
      questionSw: 'Mtume gani alimkana Yesu mara tatu kabla ya jogoo kuwika?',
      optionsEn: ['Judas', 'John', 'Peter', 'Thomas'],
      optionsSw: ['Yuda', 'Yohana', 'Petro', 'Tomaso'],
      correctAnswerIndex: 2,
      explanationEn: 'Peter denied Jesus three times out of fear, fulfilling Jesus\'s prophecy (Matthew 26).',
      explanationSw: 'Petro alimkana Yesu mara tatu kwa hofu, akitimiza unabii wa Yesu (Mathayo 26).',
    ),
    BibleQuestion(
      id: 16,
      level: 'intermediate',
      questionEn: 'What is the final book of the New Testament?',
      questionSw: 'Kitabu cha mwisho cha Agano Jipya ni kipi?',
      optionsEn: ['Jude', 'Revelation', 'Hebrews', 'Acts'],
      optionsSw: ['Yuda', 'Ufunuo', 'Waebrania', 'Matendo ya Mitume'],
      correctAnswerIndex: 1,
      explanationEn: 'The Book of Revelation (Apocalypse) is the final book, containing visions written by John.',
      explanationSw: 'Kitabu cha Ufunuo ni cha mwisho, kilichojaa maono yaliyoandikwa na Yohana.',
    ),
    BibleQuestion(
      id: 17,
      level: 'intermediate',
      questionEn: 'Who was Jacob\'s favorite son, sold into slavery in Egypt by his brothers?',
      questionSw: 'Mwana aliyependwa zaidi na Yakobo, aliyeuzwa utumwani Misri na ndugu zake alikuwa nani?',
      optionsEn: ['Benjamin', 'Reuben', 'Joseph', 'Judah'],
      optionsSw: ['Benyamini', 'Rubeni', 'Yosefu', 'Yuda'],
      correctAnswerIndex: 2,
      explanationEn: 'Joseph was sold by his jealous brothers, later rising to become governor of Egypt (Genesis 37).',
      explanationSw: 'Yosefu aliuawa (aliuzwa) na ndugu zake wenye wivu, baadaye akawa mtawala wa Misri (Mwanzo 37).',
    ),
    BibleQuestion(
      id: 18,
      level: 'intermediate',
      questionEn: 'Which prophet was swept up into heaven in a whirlwind with a chariot of fire?',
      questionSw: 'Nabii gani alichukuliwa juu mbinguni kwa upepo wa kisulisuli na gari la moto?',
      optionsEn: ['Elisha', 'Elijah', 'Isaiah', 'Ezekiel'],
      optionsSw: ['Elisha', 'Eliya', 'Isaya', 'Ezekieli'],
      correctAnswerIndex: 1,
      explanationEn: 'Elijah did not die but was carried to heaven in a chariot of fire, witnessed by Elisha (2 Kings 2).',
      explanationSw: 'Eliya hakufa bali alichukuliwa mbinguni kwa gari la moto, akishuhudiwa na Elisha (2 Wafalme 2).',
    ),
    BibleQuestion(
      id: 19,
      level: 'intermediate',
      questionEn: 'What did Jesus turn water into during His first public miracle at the Wedding in Cana?',
      questionSw: 'Yesu aligeuza maji kuwa nini katika muujiza wake wa kwanza kwenye Arusi ya Kana?',
      optionsEn: ['Milk', 'Wine', 'Olive Oil', 'Honey'],
      optionsSw: ['Maziwa', 'Divai', 'Mafuta ya Mzeituni', 'Asali'],
      correctAnswerIndex: 1,
      explanationEn: 'Jesus turned water into high-quality wine when the wedding hosts ran out (John 2).',
      explanationSw: 'Yesu aligeuza maji kuwa divai bora wakati wenyeji wa arusi walipungukiwa (Yohana 2).',
    ),
    BibleQuestion(
      id: 20,
      level: 'intermediate',
      questionEn: 'Which book in the New Testament is the shortest?',
      questionSw: 'Kitabu kifupi zaidi katika Agano Jipya ni kipi?',
      optionsEn: ['Philemon', 'Jude', '2 John', '3 John'],
      optionsSw: ['Filemoni', 'Yuda', '2 Yohana', '3 Yohana'],
      correctAnswerIndex: 3,
      explanationEn: '3 John is the shortest book in the Bible by word count (only 14 verses).',
      explanationSw: '3 Yohana ndicho kitabu kifupi zaidi katika Biblia kwa idadi ya maneno (kina aya 14 tu).',
    ),

    // --- ADVANCED ---
    BibleQuestion(
      id: 21,
      level: 'advanced',
      questionEn: 'Who was the father of King David?',
      questionSw: 'Baba yake Mfalme Daudi alikuwa nani?',
      optionsEn: ['Jesse', 'Saul', 'Samuel', 'Boaz'],
      optionsSw: ['Yese', 'Sauli', 'Samweli', 'Boazi'],
      correctAnswerIndex: 0,
      explanationEn: 'Jesse of Bethlehem was the father of David, the youngest of his eight sons (1 Samuel 16).',
      explanationSw: 'Yese wa Bethlehemu alikuwa baba yake Daudi, mdogo zaidi kati ya wanawe wanane (1 Samweli 16).',
    ),
    BibleQuestion(
      id: 22,
      level: 'advanced',
      questionEn: 'In which valley did the battle between David and Goliath take place?',
      questionSw: 'Pambano kati ya Daudi na Goliathi lilifanyika katika bonde gani?',
      optionsEn: ['Valley of Jezreel', 'Valley of Elah', 'Valley of Kidron', 'Valley of Hinom'],
      optionsSw: ['Bonde la Yezreeli', 'Bonde la Ela', 'Bonde la Kedroni', 'Bonde la Hinomu'],
      correctAnswerIndex: 1,
      explanationEn: '1 Samuel 17:2 states that Saul and the men of Israel gathered and encamped in the Valley of Elah.',
      explanationSw: '1 Samweli 17:2 inasema Sauli na watu wa Israeli walikusanyika wakapiga kambi katika Bonde la Ela.',
    ),
    BibleQuestion(
      id: 23,
      level: 'advanced',
      questionEn: 'How many chapters are contained in the Book of Isaiah?',
      questionSw: 'Kitabu cha Nabii Isaya kina sura ngapi kwa jumla?',
      optionsEn: ['40', '50', '66', '150'],
      optionsSw: ['40', '50', '66', '150'],
      correctAnswerIndex: 2,
      explanationEn: 'Isaiah contains exactly 66 chapters, mirroring the 66 books of the entire Bible.',
      explanationSw: 'Isaya kina sura 66, kikifanana na idadi ya vitabu 66 vya Biblia nzima.',
    ),
    BibleQuestion(
      id: 24,
      level: 'advanced',
      questionEn: 'What was the original Roman/Hebrew name of the Apostle Paul before his conversion on the road to Damascus?',
      questionSw: 'Jina la kwanza la kiyahudi/kirumi la Mtume Paulo kabla ya kuongoka kwake njiani kwenda Damasko lilikuwa nani?',
      optionsEn: ['Barnabas', 'Saul of Tarsus', 'Stephen', 'Silas'],
      optionsSw: ['Barnaba', 'Sauli wa Tarso', 'Stefano', 'Sila'],
      correctAnswerIndex: 1,
      explanationEn: 'Paul was known as Saul of Tarsus, a Pharisee who persecuted early Christians, before his conversion (Acts 9).',
      explanationSw: 'Paulo alijulikana kama Sauli wa Tarso, Farisayo aliyewatesa Wakristo wa kwanza, kabla ya kuongoka kwake (Matendo 9).',
    ),
    BibleQuestion(
      id: 25,
      level: 'advanced',
      questionEn: 'Who was Saul\'s son and David\'s closest friend, with whom he made a covenant?',
      questionSw: 'Mwana wa Sauli na rafiki wa karibu sana wa Daudi, ambaye alifanya naye agano, alikuwa nani?',
      optionsEn: ['Ishbosheth', 'Abner', 'Jonathan', 'Mephibosheth'],
      optionsSw: ['Ishboshethi', 'Abneri', 'Yonathani', 'Mefiboshethi'],
      correctAnswerIndex: 2,
      explanationEn: 'Jonathan loved David as his own soul, and they made a covenant of friendship (1 Samuel 18).',
      explanationSw: 'Yonathani alimpenda Daudi kama nafsi yake mwenyewe, wakafanya agano la urafiki (1 Samweli 18).',
    ),
    BibleQuestion(
      id: 26,
      level: 'advanced',
      questionEn: 'Which Jewish queen saved her people from the genocidal plot of Haman?',
      questionSw: 'Malkia gani Myahudi aliyewaokoa watu wake na njama za mauaji ya halaiki za Hamani?',
      optionsEn: ['Ruth', 'Esther', 'Judith', 'Deborah'],
      optionsSw: ['Ruthi', 'Esta', 'Yudithi', 'Debora'],
      correctAnswerIndex: 1,
      explanationEn: 'Queen Esther risked her life to appeal to King Ahasuerus and expose Haman\'s plot (Book of Esther).',
      explanationSw: 'Malkia Esta alihatarisha maisha yake kukata rufaa kwa Mfalme Ahasuero na kufichua njama za Hamani (Kitabu cha Esta).',
    ),
    BibleQuestion(
      id: 27,
      level: 'advanced',
      questionEn: 'What was the name of the high priest who presided over the Sanhedrin trial of Jesus?',
      questionSw: 'Kuhani Mkuu aliyesimamia baraza la Sanhedrini wakati wa kesi ya Yesu aliitwa nani?',
      optionsEn: ['Annas', 'Caiaphas', 'Eleazar', 'Melchizedek'],
      optionsSw: ['Ana', 'Kayafa', 'Eleazari', 'Melkizedeki'],
      correctAnswerIndex: 1,
      explanationEn: 'Caiaphas was the high priest during that year, and led the plot to put Jesus to death (Matthew 26 / John 11).',
      explanationSw: 'Kayafa alikuwa kuhani mkuu mwaka ule, akasimamia njama za kumwua Yesu (Mathayo 26 / Yohana 11).',
    ),
    BibleQuestion(
      id: 28,
      level: 'advanced',
      questionEn: 'Which tribe of Israel was set apart and omitted from receiving a geographic land inheritance in order to serve as priests?',
      questionSw: 'Kabila gani la Israeli lililotengwa na kutoruhusiwa kupokea urithi wa ardhi ili watumike kama makuhani?',
      optionsEn: ['Judah', 'Levi', 'Benjamin', 'Joseph'],
      optionsSw: ['Yuda', 'Lawi', 'Benyamini', 'Yosefu'],
      correctAnswerIndex: 1,
      explanationEn: 'The Levites did not receive land inheritance because the Lord and the priesthood was their inheritance (Joshua 13:33).',
      explanationSw: 'Walawi hawakupokea urithi wa ardhi kwa sababu Bwana na ukuhani ndio ulikuwa urithi wao (Yoshua 13:33).',
    ),
    BibleQuestion(
      id: 29,
      level: 'advanced',
      questionEn: 'In the Book of Revelation, what is the meaning of the title "Alpha and Omega"?',
      questionSw: 'Katika kitabu cha Ufunuo, maana ya jina "Alfa na Omega" ni nini?',
      optionsEn: ['The Light and the Way', 'The First and the Last', 'The Creator and Father', 'The King of Kings'],
      optionsSw: ['Nuru na Njia', 'Wa kwanza na wa Mwisho', 'Muumba na Baba', 'Mfalme wa Wafalme'],
      correctAnswerIndex: 1,
      explanationEn: 'Alpha and Omega are the first and last letters of the Greek alphabet, meaning God is the beginning and the end.',
      explanationSw: 'Alfa na Omega ni herufi ya kwanza na ya mwisho ya alfabeti ya Kigiriki, maana yake Mungu ni mwanzo na mwisho.',
    ),
    BibleQuestion(
      id: 30,
      level: 'advanced',
      questionEn: 'Who served as the faithful scribe and secretary to the prophet Jeremiah?',
      questionSw: 'Nani aliyetumika kama mwandishi mwaminifu wa nabii Yeremia?',
      optionsEn: ['Baruch', 'Esdras', 'Nehemiah', 'Habakkuk'],
      optionsSw: ['Baruki', 'Esdra', 'Nehemia', 'Habakuki'],
      correctAnswerIndex: 0,
      explanationEn: 'Baruch son of Neriah wrote down all the words of the Lord dictated by Jeremiah (Jeremiah 36).',
      explanationSw: 'Baruki mwana wa Neria aliandika maneno yote ya Bwana yaliyotamkwa na Yeremia (Yeremia 36).',
    ),
  ];
}
